### ISSUE TITLE
in the "Trapezoidal speed profile task", what does "angle a" mean? 

### ISSUE THREAD

**Issue by jvech** [kiwicampus/SD-final-project#1]
In the function get_profile_route the returned keys "t" and "dt" makes reference to "angle a". Is this "angle a" the arctan(v_a/t_a)?, where v_a and t_a are the aceleration/deceleration speed and time? or is it related with the origin and destination x and y coordinates?

```
def get_profile_route(
        self, src: tuple, dst: tuple, time: float, pt=0.3, n=30
    ) -> list:
        """
            Generates waypoints: coordinates and times with a trapezoidal profile
        Args:
            src: `tuple` origin coordinate (X, Y)
            dst: `tuple` destination coordinate (X, Y)
            time: `float` time from origin to destination
            pt: `float` deceleration/acceleration factor
            n: `int` control points to discrite the trajectory
        Returns:
            way_points: `dict` coordinates and times of trajectory with trapezoidal profile
                every element in the list is  dictionary with the keys:
                {
                    "idx": [int](index of the waypoint),
                    "pt": [tuple][int](x and y axis positions in the image space),
                    "t": [float](time for angle a),
                    "dt": [float](sept of time for angle a, is constant element)
                }
        """
```

**Comment by camilopq97** [comment]
It seems to be our mistake in the function comment. 
The `get_profile_route` function is used to generate waypoints for coordinates (x,y), so the keys `t` and `dt` refers to the time and step of time (respectively) for the specific `(X,Y)` coordinates in the `pt` parameter. 
As you may note, the comment regards to the `angle a` refers to the `get_profile_turn` function.
We will fix it, sorry for the confusion. 
Congrats, you won +3% (0.15) in your final project grade!
